### PR TITLE
Removes 5000 character limit by splitting text into sentences.

### PR DESCRIPTION
**Pull request by pgmichael**
This should remove the 5000 character limit by splitting the text into sentences.

For audio playback, the second sentence is always fetched preemptively to avoid any stuttering.

### CODE REVIEW

**Review by simsim314 — APPROVED** [review]
Checked the code - but don't understand it well. Checked the addon and it works great! 

I don't see the text labels in my extension (loaded unpack in developer mode), but I guess it's not a real issue - only with my install or something. 

wfc

**Comment by pgmichael** [comment]
Thanks for testing this @simsim314, the shortcut issue is actually caused by loading multiple extension that share the same shortcuts (we could handle this more gracefully though).

**Comment by superluig164** [comment]
I can directly see the shortcut issue myself, and I'm using the Web Store version.  I removed the shortcut to download an MP3, and so it shows up blank.

**Comment by simsim314** [comment]
I guess the shortcut issue if happens only in second addon, is not a big deal as most people aren't using the same addon twice - and if they are, no one cares that one of the menus is empty. More wanted to leave my report on what I see, to make sure it's not a real issue of text not showing in the new one or something more critical.

**Pull request merged**
